config/routes.rb
BakerServer::Engine.routes.draw do

  resources :devise_tokens

  resources :users

  resources :products, only: [:index] do
    collection do
      post "verify"
      get "download"
    end
  end

  resources :subscriptions do
    resources :products
    resources :non_renewing_subscriptions
    resources :auto_renewal_subscriptions
    resources :free_subscriptions
  end

  resources :non_consumables

  resources :issues, except: :show
  root :to => 'dashboard#index'
end

app/models/baker_server/auto_renewal_subscription.rb
module BakerServer
  class AutoRenewalSubscription < Product

    validates_presence_of :subscription
    validates_presence_of :subscription_duration

    belongs_to :subscription

    belongs_to :subscription_duration
  end
end

app/models/baker_server/devise_token.rb
module BakerServer
  class DeviseToken < ActiveRecord::Base
    belongs_to :user
    validates_presence_of :token
  end
end

app/models/baker_server/free_subscription.rb
module BakerServer
  class FreeSubscription < Product
    validates_presence_of :subscription
    belongs_to :subscription
  end
end

app/models/baker_server/issue.rb
module BakerServer
  class Issue < ActiveRecord::Base
    validates_presence_of :issue_id
    validates_presence_of :published_date
    validates_presence_of :summary
    validates_length_of :summary, :maximum => 2000
    validate :published_date_order

    image_accessor :cover_art

    protected
    def published_date_order
      if self.end_date && (self.published_date > self.end_date)
        self.errors.add(:published_date, "Published date should be less than end date")
      end
    end

  end
end

#More Validations
#cover art should be a png file
#It should have 512px

#Instead of having one cover art user can submit multiple cover arts for various devises

app/models/baker_server/non_consumable.rb
module BakerServer
  class NonConsumable < Product

  end
end

app/models/baker_server/non_renewing_subscription.rb
module BakerServer
  class NonRenewingSubscription < Product

    validates_presence_of :subscription
    belongs_to :subscription

  end
end

app/models/baker_server/product.rb
module BakerServer
  class Product < ActiveRecord::Base

    validates_presence_of :product_id

    image_accessor :icon
    image_accessor :preview
    file_accessor :content

    scope :subscriptions, where("subscription_id is not null")
    scope :products, where("subscription_id is null")

  end
end

app/models/baker_server/subscription.rb
module BakerServer
  class Subscription < ActiveRecord::Base
    validates_presence_of :name
    has_many :products, :dependent => :destroy
    has_many :auto_renewal_subscriptions
    has_many :free_subscriptions
    has_many :non_renewing_subscriptions
  end
end

app/models/baker_server/subscription_duration.rb
module BakerServer
  class SubscriptionDuration < ActiveRecord::Base
    validates_presence_of :name
    has_many :auto_renewal_subscriptions
  end
end

app/models/baker_server/user.rb
module BakerServer
  class User < ActiveRecord::Base
    has_many :devise_tokens

    before_create :new_random_password

    protected
    def new_random_password
      self.password = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{email_address}--")[0, 6]
    end
  end
end

app/controllers/baker_server/application_controller.rb
module BakerServer
  class ApplicationController < ActionController::Base
  end
end

app/controllers/baker_server/auto_renewal_subscriptions_controller.rb
module BakerServer
  class AutoRenewalSubscriptionsController < ProductsController
    inherit_resources

    defaults :resource_class => BakerServer::AutoRenewalSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true

    actions :all
    respond_to :html

  end
end

app/controllers/baker_server/dashboard_controller.rb
module BakerServer
  class DashboardController < ApplicationController

    caches_page :index

    def index
    end
  end
end

app/controllers/baker_server/devise_tokens_controller.rb
module BakerServer
  class DeviseTokensController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html
    respond_to :json

    def create
      #puts "########################"
      #puts params
      #puts "########################"
      create! { devise_tokens_path }
    end

    def update
      update! { devise_tokens_path }
    end

    def destroy
      destroy! { devise_tokens_path }
    end

  end
end

app/controllers/baker_server/free_subscriptions_controller.rb
module BakerServer
  class FreeSubscriptionsController < ProductsController
    inherit_resources
    actions :all
    respond_to :html

    defaults :resource_class => BakerServer::FreeSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true

  end
end

app/controllers/baker_server/issues_controller.rb
module BakerServer
  class IssuesController < ApplicationController
    inherit_resources
    actions :all, :except => :show
    respond_to :html, :except => :download
    respond_to :atom, :only => :index

    def create
      create! { issues_url }
    end

    def update
      update! { issues_url }
    end

    def destroy
      destroy! { issues_url }
    end

    protected
    def collection
      @issues ||= end_of_association_chain.order("published_date")
    end
  end
end

app/controllers/baker_server/non_consumables_controller.rb
module BakerServer
  class NonConsumablesController < ProductsController

    inherit_resources
    defaults :resource_class => BakerServer::NonConsumable
    actions :all
    respond_to :html
    #TODO This should not be there. Added because of an issue.
    belongs_to :subscription, parent_class: Subscription, optional: true

    def create
      create! { non_consumables_url }
    end

    def update
      update! { non_consumables_url }
    end

    def destroy
      destroy! { non_consumables_url }
    end

  end
end

app/controllers/baker_server/non_renewing_subscriptions_controller.rb
module BakerServer
  class NonRenewingSubscriptionsController < ProductsController
    inherit_resources
    actions :all
    respond_to :html

    defaults :resource_class => BakerServer::NonRenewingSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true
  end
end

app/controllers/baker_server/products_controller.rb
require "baker_server/app_store_receipt_validation.rb"

module BakerServer
  class ProductsController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html
    respond_to :json, :only => [:index, :verify, :download]
    belongs_to :subscription, parent_class: Subscription, optional: true

    has_scope :subscriptions, :type => :boolean
    has_scope :products, :type => :boolean

    def create
      create! { subscription_products_path(parent) }
    end

    def update
      update! { subscription_products_path(parent) }
    end

    def destroy
      destroy! { subscription_products_path(parent) }
    end

    def verify
      subscription  = !BakerServer::NonConsumable.exists?(:name => params[:productIdentifier])
      file_contents = read_receipt(params[:receipt])
      user          = BakerServer::User.find_by_id_and_password(params[:user_id], params[:user_password])
      if subscription
        @server_response = ::BakerServer::AppStoreReceiptValidation.validate_subscription(file_contents, true)
        json = ActiveSupport::JSON.decode(@server_response)
        puts ['original_purchase_date_pst', 'original_transaction_id', 'expires_date', 'transaction_id', 'quantity',
         'product_id', 'web_order_line_item_id', 'item_id', 'expires_date_formatted', 'purchase_date', 'purchase_date_ms',
         'expires_date_formatted_pst', 'purchase_date_pst', 'original_purchase_date', 'original_purchase_date_ms'].collect{|e|json['receipt'][e]}.join("\t")
        puts ['original_purchase_date_pst', 'original_transaction_id', 'expires_date', 'transaction_id', 'quantity',
        'product_id', 'web_order_line_item_id', 'item_id', 'expires_date_formatted', 'purchase_date', 'purchase_date_ms',
        'expires_date_formatted_pst', 'purchase_date_pst', 'original_purchase_date', 'original_purchase_date_ms'].collect{|e|json['latest_receipt_info'][e]}.join("\t")
      else
        @server_response = ::BakerServer::AppStoreReceiptValidation.validate_non_consumable(file_contents, true)
      end
    end

    def download
      @product      = BakerServer::Product.find_by_product_id params[:product_identifier]
      @download_url = @product.content.url
    end

    private
    def read_receipt(file_data)
      if file_data.respond_to?(:read)
        return file_data.read
      elsif file_data.respond_to?(:path)
        return File.read(file_data.path)
      else
        logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
      end
    end

  end
end

app/controllers/baker_server/subscriptions_controller.rb
module BakerServer
  class SubscriptionsController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html

    def create
      create! { subscriptions_url }
    end

    def update
      update! { subscriptions_url }
    end

    def destroy
      destroy! { subscriptions_url }
    end

  end
end

app/views/baker_server/products/_form.html.haml
= simple_form_for([parent, resource], :html => {:class => 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :product_id, label: 'Product ID', input_html: { class: "span6" }, hint: 'A unique identifier that will be used for reporting. It can be composed of letters and numbers.'
    = f.input :name, input_html: { class: "span6" }, hint: ''
    = f.input :paid, input_html: { class: "span6" }, hint: 'If paid option is selected we will check with App store to verify about the transaction before providing a download url.'
    = f.input :description, input_html: { class: "span6", rows: 8 }, hint: ''
    = f.input :content, as: :file, input_html: { class: "span6" }, hint: ''
    = f.input :icon, as: :file, input_html: { class: "span6" }, hint: ''
    = f.input :preview, as: :file, input_html: { class: "span6" }, hint: ''

  .form-actions
    = f.button :submit

app/views/baker_server/products/edit.html.haml
.well
  %h1 Editing #{resource_class.to_s.demodulize.titleize}

= render 'form'

= link_to 'Show', polymorphic_path([parent, resource])
-#\|
-#= link_to 'Back', products_path

app/views/baker_server/products/index.html.haml
.well
  %h1 Listing products

%table#productsTable.table.table-bordered.table-striped.tablesorter
  %thead
    %tr
      %th Product
      %th Type
      %th{width: "110px"} Icon
      %th{width: "110px"} Preview
      %th{width: "200px"}  Actions

  %tbody
    - collection.each do |product|
      %tr
        %td= product.product_id
        %td= product.class.to_s.demodulize.titleize
        %td= render_image(product.icon)
        %td= render_image(product.preview)
        %td
          = link_to 'Show', polymorphic_path([parent, product]), :class => 'btn btn-mini'
          = link_to 'Edit', edit_polymorphic_path([parent, product]), :class => 'btn btn-mini'
          = link_to 'Destroy', polymorphic_path([parent, product]), :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger'

.btn-group
  %a.btn.btn-primary.dropdown-toggle{data: {toggle: "dropdown"}, href: "#"}
    Create Product
    %span.caret
  %ul.dropdown-menu
    = link_to 'New Auto Renewing Subscription', new_subscription_auto_renewal_subscription_path(parent)
    = link_to 'New Free Subscription', new_subscription_free_subscription_path(parent)
    = link_to 'New Non Renewing Subscription', new_subscription_non_renewing_subscription_path(parent)

:javascript
  jQuery(function($) {
    $("#productsTable").tablesorter({
      sortList: [[1,0]],
      headers: {
        0: {
          sorter: false
        },
        2: {
          sorter: false
        },
        3: {
          sorter: false
        },
        4: {
          sorter: false
        }
      }
    });
  });

app/views/baker_server/products/new.html.haml
.well
  %h1 New #{resource_class.to_s.demodulize.titleize}

= render 'form'

-#= link_to 'Back', collection_path(resource)

app/views/baker_server/products/show.html.haml
%p#notice= notice

%p
  %b Product:
  = resource.product_id
%p
  %b Content uid:
  = resource.content_uid
%p
  %b Name:
  = resource.name
%p
  %b Icon uid:
  = resource.icon_uid
%p
  %b Preview uid:
  = resource.preview_uid
%p
  %b Description:
  = resource.description
%p
  %b Paid:
  = resource.paid

.form-actions
  = link_to 'Edit', edit_polymorphic_path([parent, resource]), :class => 'btn'

  -#= link_to 'Back', collection_path(resource_class.new), :class => 'btn'

app/views/baker_server/products/verify.json.haml
= @server_response.html_safe