config/routes.rb
BakerServer::Engine.routes.draw do

  resources :devise_tokens

  resources :users

  resources :products, only: [:index] do
    collection do
      post "verify"
      get "download"
    end
  end

  resources :subscriptions do
    resources :products
    resources :non_renewing_subscriptions
    resources :auto_renewal_subscriptions
    resources :free_subscriptions
  end

  resources :non_consumables

  resources :issues, except: :show
  root :to => 'dashboard#index'
end

app/models/baker_server/auto_renewal_subscription.rb
module BakerServer
  class AutoRenewalSubscription < Product

    validates_presence_of :subscription
    validates_presence_of :subscription_duration

    belongs_to :subscription

    belongs_to :subscription_duration
  end
end

app/models/baker_server/devise_token.rb
module BakerServer
  class DeviseToken < ActiveRecord::Base
    belongs_to :user
    validates_presence_of :token
  end
end

app/models/baker_server/free_subscription.rb
module BakerServer
  class FreeSubscription < Product
    validates_presence_of :subscription
    belongs_to :subscription
  end
end

app/models/baker_server/issue.rb
module BakerServer
  class Issue < ActiveRecord::Base
    validates_presence_of :issue_id
    validates_presence_of :published_date
    validates_presence_of :summary
    validates_length_of :summary, :maximum => 2000
    validate :published_date_order

    image_accessor :cover_art

    protected
    def published_date_order
      if self.end_date && (self.published_date > self.end_date)
        self.errors.add(:published_date, "Published date should be less than end date")
      end
    end

  end
end

#More Validations
#cover art should be a png file
#It should have 512px

#Instead of having one cover art user can submit multiple cover arts for various devises

app/models/baker_server/non_consumable.rb
module BakerServer
  class NonConsumable < Product

  end
end

app/models/baker_server/non_renewing_subscription.rb
module BakerServer
  class NonRenewingSubscription < Product

    validates_presence_of :subscription
    belongs_to :subscription

  end
end

app/models/baker_server/product.rb
module BakerServer
  class Product < ActiveRecord::Base

    validates_presence_of :product_id

    image_accessor :icon
    image_accessor :preview
    file_accessor :content

    scope :subscriptions, where("subscription_id is not null")
    scope :products, where("subscription_id is null")

  end
end

app/models/baker_server/subscription.rb
module BakerServer
  class Subscription < ActiveRecord::Base
    validates_presence_of :name
    has_many :products, :dependent => :destroy
    has_many :auto_renewal_subscriptions
    has_many :free_subscriptions
    has_many :non_renewing_subscriptions
  end
end

app/models/baker_server/subscription_duration.rb
module BakerServer
  class SubscriptionDuration < ActiveRecord::Base
    validates_presence_of :name
    has_many :auto_renewal_subscriptions
  end
end

app/models/baker_server/user.rb
module BakerServer
  class User < ActiveRecord::Base
    has_many :devise_tokens

    before_create :new_random_password

    protected
    def new_random_password
      self.password = Digest::SHA1.hexdigest("--#{Time.now.to_s}--#{email_address}--")[0, 6]
    end
  end
end

app/controllers/baker_server/application_controller.rb
module BakerServer
  class ApplicationController < ActionController::Base
  end
end

app/controllers/baker_server/auto_renewal_subscriptions_controller.rb
module BakerServer
  class AutoRenewalSubscriptionsController < ProductsController
    inherit_resources

    defaults :resource_class => BakerServer::AutoRenewalSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true

    actions :all
    respond_to :html

  end
end

app/controllers/baker_server/dashboard_controller.rb
module BakerServer
  class DashboardController < ApplicationController

    caches_page :index

    def index
    end
  end
end

app/controllers/baker_server/devise_tokens_controller.rb
module BakerServer
  class DeviseTokensController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html
    respond_to :json

    def create
      #puts "########################"
      #puts params
      #puts "########################"
      create! { devise_tokens_path }
    end

    def update
      update! { devise_tokens_path }
    end

    def destroy
      destroy! { devise_tokens_path }
    end

  end
end

app/controllers/baker_server/free_subscriptions_controller.rb
module BakerServer
  class FreeSubscriptionsController < ProductsController
    inherit_resources
    actions :all
    respond_to :html

    defaults :resource_class => BakerServer::FreeSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true

  end
end

app/controllers/baker_server/issues_controller.rb
module BakerServer
  class IssuesController < ApplicationController
    inherit_resources
    actions :all, :except => :show
    respond_to :html, :except => :download
    respond_to :atom, :only => :index

    def create
      create! { issues_url }
    end

    def update
      update! { issues_url }
    end

    def destroy
      destroy! { issues_url }
    end

    protected
    def collection
      @issues ||= end_of_association_chain.order("published_date")
    end
  end
end

app/controllers/baker_server/non_consumables_controller.rb
module BakerServer
  class NonConsumablesController < ProductsController

    inherit_resources
    defaults :resource_class => BakerServer::NonConsumable
    actions :all
    respond_to :html
    #TODO This should not be there. Added because of an issue.
    belongs_to :subscription, parent_class: Subscription, optional: true

    def create
      create! { non_consumables_url }
    end

    def update
      update! { non_consumables_url }
    end

    def destroy
      destroy! { non_consumables_url }
    end

  end
end

app/controllers/baker_server/non_renewing_subscriptions_controller.rb
module BakerServer
  class NonRenewingSubscriptionsController < ProductsController
    inherit_resources
    actions :all
    respond_to :html

    defaults :resource_class => BakerServer::NonRenewingSubscription
    belongs_to :subscription, parent_class: Subscription, optional: true
  end
end

app/controllers/baker_server/products_controller.rb
require "baker_server/app_store_receipt_validation.rb"

module BakerServer
  class ProductsController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html
    respond_to :json, :only => [:index, :verify, :download]
    belongs_to :subscription, parent_class: Subscription, optional: true

    has_scope :subscriptions, :type => :boolean
    has_scope :products, :type => :boolean

    def create
      create! { subscription_products_path(parent) }
    end

    def update
      update! { subscription_products_path(parent) }
    end

    def destroy
      destroy! { subscription_products_path(parent) }
    end

    def verify
      subscription  = !BakerServer::NonConsumable.exists?(:name => params[:productIdentifier])
      file_contents = read_receipt(params[:receipt])
      user          = BakerServer::User.find_by_id_and_password(params[:user_id], params[:user_password])
      if subscription
        @server_response = ::BakerServer::AppStoreReceiptValidation.validate_subscription(file_contents, true)
        json = ActiveSupport::JSON.decode(@server_response)
        puts ['original_purchase_date_pst', 'original_transaction_id', 'expires_date', 'transaction_id', 'quantity',
         'product_id', 'web_order_line_item_id', 'item_id', 'expires_date_formatted', 'purchase_date', 'purchase_date_ms',
         'expires_date_formatted_pst', 'purchase_date_pst', 'original_purchase_date', 'original_purchase_date_ms'].collect{|e|json['receipt'][e]}.join("\t")
        puts ['original_purchase_date_pst', 'original_transaction_id', 'expires_date', 'transaction_id', 'quantity',
        'product_id', 'web_order_line_item_id', 'item_id', 'expires_date_formatted', 'purchase_date', 'purchase_date_ms',
        'expires_date_formatted_pst', 'purchase_date_pst', 'original_purchase_date', 'original_purchase_date_ms'].collect{|e|json['latest_receipt_info'][e]}.join("\t")
      else
        @server_response = ::BakerServer::AppStoreReceiptValidation.validate_non_consumable(file_contents, true)
      end
    end

    def download
      @product      = BakerServer::Product.find_by_product_id params[:product_identifier]
      @download_url = @product.content.url
    end

    private
    def read_receipt(file_data)
      if file_data.respond_to?(:read)
        return file_data.read
      elsif file_data.respond_to?(:path)
        return File.read(file_data.path)
      else
        logger.error "Bad file_data: #{file_data.class.name}: #{file_data.inspect}"
      end
    end

  end
end

app/controllers/baker_server/subscriptions_controller.rb
module BakerServer
  class SubscriptionsController < ApplicationController

    inherit_resources
    actions :all
    respond_to :html

    def create
      create! { subscriptions_url }
    end

    def update
      update! { subscriptions_url }
    end

    def destroy
      destroy! { subscriptions_url }
    end

  end
end

app/views/baker_server/issues/_form.html.haml
= simple_form_for(@issue, :html => {:class => 'form-horizontal'}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :issue_id, input_html: { class: "span6" }, hint: 'This is an internal identifier that will not be visible on the App Store.'
    = f.input :summary, input_html: { class: "span6", rows: 8 }, hint: 'This is the summary of the issue that will be seen by customers on the App Store. The summary cannot be longer than 2000 bytes.'
    = f.input :published_date, input_html: { class: "span1" }, hint: 'The date this issue will be available on the App Store (it will be displayed at the beginning of the day).'
    = f.input :end_date, input_html: { class: "span1" }, hint: 'The date this issue will be removed from the App Store (it will be removed at the beginning of the day). For example, a special one-day issue would not be added and removed on the same date. Rather, it would be removed at the beginning of the next day.'
    = f.input :cover_art, as: :file, hint: 'The cover art that will be displayed on the App Store while this issue is current. The cover art must be a .png file, at least 72 DPI, a minimum of 512 pixels on the long edge, and it must have an aspect ratio between 1:2 and 2:1. Also, the artwork must be flat with no rounded corners. Please note that if you do not add Issue Cover Art, your Newsstand Default Cover art will be displayed on the App Store for that version.'

  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/baker_server/issues/edit.html.haml
.well
  %h1 Editing issue

= render 'form'

= link_to 'Show', @issue
\|
= link_to 'Back', issues_path

app/views/baker_server/issues/index.html.haml
.well
  %h1 Listing issues

%table#listingsTable.table.table-bordered.table-striped.tablesorter
  %thead
    %tr
      %th{width: "110px"} Cover Art
      %th Issue Id
      %th Summary
      %th Published Date
      %th End Date
      %th Options

  %tbody
    - @issues.each do |issue|
      %tr
        %td= render_image(issue.cover_art)
        %td= issue.issue_id
        %td= issue.summary
        %td= issue.published_date
        %td= issue.end_date
        %td
          = link_to 'Edit', edit_issue_path(issue)
          |
          = link_to 'Destroy', issue, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Issue', new_issue_path, class: 'btn btn-primary'
%hr
.alert.alert-info
  %i.icon-info-sign
  Atom feed URL: #{link_to issues_url(format: 'atom'), issues_path(format: 'atom')}

:javascript
  jQuery(function($) {
    $("#listingsTable").tablesorter({
      sortList: [[4,1],[1,0]],
      headers: {
        0: {
          sorter: false
        },
        5: {
          sorter: false
        }
      }
    });
  });

app/views/baker_server/issues/new.html.haml
.well
  %h1 New issue

= render 'form'

= link_to 'Back', issues_path